#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dockerfoolery_development
  username: <%= ENV['DOCKERFOOLERY_DB_1_ENV_POSTGRES_USER'] %>
  password: <%= ENV['DOCKERFOOLERY_DB_1_ENV_POSTGRES_PASSWORD'] %>

  host: <%= ENV['DOCKERFOOLERY_DB_1_PORT_5432_TCP_ADDR'] %>

  #port: 5432

test:
  <<: *default
  database: dockerfoolery_test

production:
  <<: *default
  database: dockerfoolery_production
  username: dockerfoolery
  password: <%= ENV['DOCKERFOOLERY_DATABASE_PASSWORD'] %>
